"""
Hand-authored B-roll shot list for hydration.txt — one concrete visual per
scene, matched to the line's meaning, using recurring motifs (glass of water,
dark bedroom, tired person waking, kidneys, coffee) for a cohesive
health-documentary look. Writes the keywords into the plan JSON.
"""
import json
import sys

SHOTS = {
    1: ["city", "night", "lights"],
    2: ["thirsty", "man", "drinking"],
    3: ["taking", "pills", "water"],
    4: ["drinking", "water", "night"],
    5: ["man", "waking", "night"],
    6: ["bathroom", "door", "night"],
    7: ["alarm", "clock", "night"],
    8: ["senior", "man", "tired"],
    9: ["doctor", "medical", "consultation"],
    10: ["pouring", "water", "glass"],
    11: ["drinking", "water", "glass"],
    12: ["glass", "water", "morning"],
    13: ["woman", "drinking", "water"],
    14: ["swollen", "ankle", "leg"],
    15: ["senior", "man", "thinking"],
    16: ["bathroom", "light", "night"],
    17: ["man", "sleeping", "bed"],
    18: ["awake", "bed", "night"],
    19: ["alarm", "clock", "bedside"],
    20: ["bathroom", "light", "dark"],
    21: ["kidney", "anatomy", "medical"],
    22: ["pouring", "alcohol", "glass"],
    23: ["man", "urgent", "bathroom"],
    24: ["doctor", "medical", "chart"],
    25: ["man", "thinking", "night"],
    26: ["man", "lying", "awake"],
    27: ["woman", "insomnia", "bed"],
    28: ["man", "awake", "dark"],
    29: ["doctor", "patient", "talking"],
    30: ["thinking", "man", "serious"],
    31: ["pouring", "water", "glass"],
    32: ["glass", "clean", "water"],
    33: ["morning", "sunrise", "window"],
    34: ["woman", "drinking", "water"],
    35: ["water", "splash", "glass"],
    36: ["morning", "light", "window"],
    37: ["coffee", "cup", "morning"],
    38: ["coffee", "morning", "cup"],
    39: ["busy", "office", "work"],
    40: ["dinner", "table", "evening"],
    41: ["kidney", "anatomy", "medical"],
    42: ["blood", "cells", "medical"],
    43: ["kidney", "medical", "animation"],
    44: ["glass", "water", "bedside"],
    45: ["sunrise", "morning", "window"],
    46: ["pouring", "water", "glass"],
    47: ["glass", "water", "measuring"],
    48: ["glass", "water", "hand"],
    49: ["large", "water", "bottle"],
    50: ["water", "overflow", "glass"],
    51: ["woman", "sleeping", "peaceful"],
    52: ["breakfast", "table", "morning"],
    53: ["woman", "smiling", "water"],
    54: ["active", "people", "daytime"],
    55: ["woman", "sleeping", "deep"],
    56: ["drinking", "water", "glass"],
    57: ["pouring", "water", "glass"],
    58: ["water", "bottle", "drinking"],
    59: ["water", "glass", "calm"],
    60: ["lunch", "table", "water"],
    61: ["different", "people", "group"],
    62: ["doctor", "health", "checkup"],
    63: ["desert", "heat", "sun"],
    64: ["doctor", "patient", "hospital"],
    65: ["clock", "time", "hand"],
    66: ["water", "bottle", "evening"],
    67: ["woman", "drinking", "daytime"],
    68: ["running", "exercise", "water"],
    69: ["clock", "evening", "time"],
    70: ["glass", "water", "small"],
    71: ["clock", "night", "bedroom"],
    72: ["evening", "clock", "water"],
    73: ["small", "glass", "water"],
    74: ["sip", "water", "glass"],
    75: ["pills", "water", "bedside"],
    76: ["water", "bottle", "nightstand"],
    77: ["drinking", "water", "night"],
    78: ["man", "awake", "bed"],
    79: ["tired", "man", "night"],
    80: ["man", "sleepless", "bed"],
    81: ["small", "glass", "water"],
    82: ["glass", "water", "table"],
    83: ["sipping", "water", "slowly"],
    84: ["drinking", "water", "fast"],
    85: ["sipping", "glass", "water"],
    86: ["sip", "water", "glass"],
    87: ["dry", "mouth", "thirsty"],
    88: ["thinking", "confused", "man"],
    89: ["snoring", "man", "sleep"],
    90: ["pouring", "water", "glass"],
    91: ["tired", "man", "morning"],
    92: ["man", "breathing", "sleep"],
    93: ["sleep", "apnea", "man"],
    94: ["medical", "sleep", "study"],
    95: ["man", "sleeping", "monitor"],
    96: ["man", "awake", "frustrated"],
    97: ["water", "bottle", "table"],
    98: ["sleep", "clinic", "monitor"],
    99: ["coffee", "tea", "drinks"],
    100: ["coffee", "cup", "pouring"],
    101: ["coffee", "beans", "cup"],
    102: ["coffee", "cup", "evening"],
    103: ["woman", "light", "sleep"],
    104: ["coffee", "afternoon", "cup"],
    105: ["coffee", "cup", "clock"],
    106: ["coffee", "morning", "sunrise"],
    107: ["calendar", "days", "time"],
    108: ["tea", "cup", "pouring"],
    109: ["senior", "tea", "cup"],
}

if __name__ == "__main__":
    path = sys.argv[1]
    plan = json.load(open(path))
    missing = [s["scene"] for s in plan if s["scene"] not in SHOTS]
    if missing:
        raise SystemExit(f"No shot authored for scenes: {missing}")
    for s in plan:
        s["keywords"] = SHOTS[s["scene"]]
    json.dump(plan, open(path, "w"), indent=2)
    print(f"Applied {len(SHOTS)} authored shots to {path}")
