"""
Hand-authored B-roll shot list for hydration.txt — one concrete visual per
scene, matched to the line's meaning, using recurring motifs (glass of water,
dark bedroom, tired person waking, kidneys, coffee) for a cohesive
health-documentary look. Writes the keywords into the plan JSON.
"""
import json
import sys

# Each shot leads with a reliable, well-stocked ANCHOR noun (water, man,
# bedroom, coffee, clock, doctor, kidney...) so that even when the search
# broadens (all keywords -> first two -> first one) the fallback stays on
# topic. Niche/adjective-first queries (e.g. "thirsty", "taking") were the
# cause of off-topic clips (a wasp, a hand with a card) and are avoided.
SHOTS = {
    1: ["city", "night", "traffic"],
    2: ["man", "drinking", "water"],
    3: ["hand", "pills", "medicine"],
    4: ["water", "glass", "night"],
    5: ["man", "sleeping", "bed"],
    6: ["bathroom", "night", "light"],
    7: ["clock", "bedside", "night"],
    8: ["senior", "man", "tired"],
    9: ["doctor", "patient", "consultation"],
    10: ["water", "pouring", "glass"],
    11: ["water", "drinking", "glass"],
    12: ["water", "glass", "morning"],
    13: ["woman", "drinking", "water"],
    14: ["legs", "feet", "swollen"],
    15: ["man", "thinking", "serious"],
    16: ["bathroom", "night", "door"],
    17: ["man", "sleeping", "bed"],
    18: ["man", "awake", "bed"],
    19: ["clock", "bedside", "alarm"],
    20: ["bathroom", "night", "dark"],
    21: ["kidney", "anatomy", "medical"],
    22: ["alcohol", "pouring", "glass"],
    23: ["man", "bathroom", "door"],
    24: ["doctor", "medical", "chart"],
    25: ["man", "thinking", "bed"],
    26: ["man", "awake", "lying"],
    27: ["woman", "insomnia", "bed"],
    28: ["man", "awake", "dark"],
    29: ["doctor", "patient", "talking"],
    30: ["man", "thinking", "serious"],
    31: ["water", "pouring", "glass"],
    32: ["water", "glass", "clean"],
    33: ["morning", "sunrise", "window"],
    34: ["woman", "drinking", "water"],
    35: ["water", "splash", "glass"],
    36: ["morning", "light", "window"],
    37: ["coffee", "morning", "cup"],
    38: ["coffee", "cup", "morning"],
    39: ["office", "work", "busy"],
    40: ["dinner", "table", "evening"],
    41: ["kidney", "anatomy", "medical"],
    42: ["blood", "medical", "cells"],
    43: ["kidney", "medical", "anatomy"],
    44: ["water", "glass", "bedside"],
    45: ["morning", "sunrise", "window"],
    46: ["water", "pouring", "glass"],
    47: ["water", "glass", "pouring"],
    48: ["water", "glass", "hand"],
    49: ["water", "bottle", "large"],
    50: ["water", "overflowing", "glass"],
    51: ["woman", "sleeping", "peaceful"],
    52: ["breakfast", "table", "morning"],
    53: ["woman", "water", "smiling"],
    54: ["people", "walking", "daytime"],
    55: ["woman", "sleeping", "bed"],
    56: ["water", "drinking", "glass"],
    57: ["water", "pouring", "glass"],
    58: ["water", "bottle", "drinking"],
    59: ["water", "glass", "calm"],
    60: ["lunch", "table", "water"],
    61: ["people", "group", "diverse"],
    62: ["doctor", "checkup", "health"],
    63: ["desert", "sun", "heat"],
    64: ["doctor", "hospital", "patient"],
    65: ["clock", "time", "hand"],
    66: ["water", "bottle", "evening"],
    67: ["woman", "drinking", "water"],
    68: ["running", "exercise", "outdoor"],
    69: ["clock", "evening", "time"],
    70: ["water", "glass", "small"],
    71: ["bedroom", "clock", "night"],
    72: ["clock", "evening", "water"],
    73: ["water", "glass", "small"],
    74: ["water", "glass", "sip"],
    75: ["pills", "water", "bedside"],
    76: ["water", "bottle", "nightstand"],
    77: ["water", "drinking", "night"],
    78: ["man", "awake", "bed"],
    79: ["man", "tired", "night"],
    80: ["man", "sleepless", "bed"],
    81: ["water", "glass", "small"],
    82: ["water", "glass", "table"],
    83: ["water", "sipping", "slowly"],
    84: ["water", "drinking", "fast"],
    85: ["water", "sipping", "glass"],
    86: ["water", "glass", "sip"],
    87: ["man", "thirsty", "mouth"],
    88: ["man", "confused", "thinking"],
    89: ["man", "snoring", "sleep"],
    90: ["water", "pouring", "glass"],
    91: ["man", "tired", "morning"],
    92: ["man", "sleeping", "breathing"],
    93: ["man", "sleep", "apnea"],
    94: ["sleep", "study", "medical"],
    95: ["man", "sleeping", "monitor"],
    96: ["man", "awake", "frustrated"],
    97: ["water", "bottle", "table"],
    98: ["sleep", "clinic", "monitor"],
    99: ["coffee", "tea", "cups"],
    100: ["coffee", "pouring", "cup"],
    101: ["coffee", "cup", "beans"],
    102: ["coffee", "cup", "evening"],
    103: ["woman", "sleeping", "light"],
    104: ["coffee", "cup", "afternoon"],
    105: ["coffee", "cup", "clock"],
    106: ["coffee", "morning", "sunrise"],
    107: ["calendar", "days", "time"],
    108: ["tea", "pouring", "cup"],
    109: ["tea", "cup", "senior"],
}

if __name__ == "__main__":
    path = sys.argv[1]
    plan = json.load(open(path))
    missing = [s["scene"] for s in plan if s["scene"] not in SHOTS]
    if missing:
        raise SystemExit(f"No shot authored for scenes: {missing}")
    for s in plan:
        s["keywords"] = SHOTS[s["scene"]]
    json.dump(plan, open(path, "w"), indent=2)
    print(f"Applied {len(SHOTS)} authored shots to {path}")
